const {Router} = require('express')
const router = Router()
const NewsController = require('../controllers/views.controller')
const authMiddlewere = require("../middlewere/auth.middlewere");
const SkillController = require("../controllers/skill.controller");

router.get('/news',NewsController.getNews)
router.post('/createpost',authMiddlewere,NewsController.createPost)
router.post('/plusaup',authMiddlewere,NewsController.plusAUP)
router.post('/updatemanaup',authMiddlewere,NewsController.updateManAUP)
router.get('/getaup',NewsController.getAUP)
router.post('/delman',authMiddlewere,NewsController.delMan)
router.post('/plusvideo',authMiddlewere,NewsController.plusVideo)
router.post('/pluscomvak',authMiddlewere,NewsController.plusComVak)
router.get('/getcomvak',authMiddlewere,NewsController.getComVak)
router.post('/delcomvak',authMiddlewere,NewsController.delComVak)
router.post('/createvak',authMiddlewere,NewsController.createVak)
router.get('/getvakansii',authMiddlewere,NewsController.getVakansii)
router.post('/editvak',authMiddlewere,NewsController.editVak)
router.post('/deltisvak',authMiddlewere,NewsController.delTisVak)
router.post('/getabout',authMiddlewere,NewsController.getAbout)
router.post('/saveabout',authMiddlewere,NewsController.saveAbout)
router.post('/pluscompany',authMiddlewere,NewsController.plusCompany)
router.get('/getgroupcompanyes',authMiddlewere,NewsController.getGroupCompanyes)
router.post('/delcomgroup',authMiddlewere,NewsController.delComGroup)
router.post('/editcomgroup',authMiddlewere,NewsController.editСomGroup)
router.post('/updateposcomgroup',authMiddlewere,NewsController.updatePosComGroup)
router.post('/getplaces',authMiddlewere,NewsController.getPlaces)
router.post('/plusplaces',authMiddlewere,NewsController.plusPlaces)
router.post('/delplace',authMiddlewere,NewsController.delPlace)
router.post('/createPack',authMiddlewere,NewsController.createpack)
router.post('/getallpacks',authMiddlewere,NewsController.getAllPacks)
router.post('/editpriorypack',authMiddlewere,NewsController.editPrioryPack)
router.post('/updatepack',authMiddlewere,NewsController.updatePack)
router.post('/createimggallery',authMiddlewere,NewsController.createImgGallery)
router.post('/getgalleryimgs',authMiddlewere,NewsController.getGalleryImgs)
router.post('/getcities',authMiddlewere,NewsController.getCities)
router.post('/createcity',authMiddlewere,NewsController.createCity)
router.post('/uploadstaticcontact',authMiddlewere,NewsController.uploadStaticContact)
router.post('/pluscontactparam',authMiddlewere,NewsController.plusContactParam)
router.post('/createzone',authMiddlewere,NewsController.createZone)
router.post('/getzones',authMiddlewere,NewsController.getZones)
router.post('/updatezone',authMiddlewere,NewsController.updateZone)

module.exports = router